-- Seed the 30-skill catalog from docs/refactor/11-rules-catalog.md.
-- Idempotent: re-running the migration does not duplicate rows.
INSERT INTO "skill" ("name", "attribute") VALUES
	('Erudição', 'cognition'),
	('Estratégia', 'cognition'),
	('Linguística', 'cognition'),
	('Lógica', 'cognition'),
	('Retórica', 'cognition'),
	('Atuação', 'psyche'),
	('Carisma', 'psyche'),
	('Compostura', 'psyche'),
	('Empatia', 'psyche'),
	('Presença', 'psyche'),
	('Criatividade', 'instinct'),
	('Pressentimento', 'instinct'),
	('Reminiscência', 'instinct'),
	('Perspectiva', 'instinct'),
	('Impressão', 'instinct'),
	('Condicionamento', 'constitution'),
	('Fortitude', 'constitution'),
	('Primalidade', 'constitution'),
	('Tolerância', 'constitution'),
	('Vitalidade', 'constitution'),
	('Expressividade', 'motricity'),
	('Manipulação', 'motricity'),
	('Mobilidade', 'motricity'),
	('Precisão', 'motricity'),
	('Reflexo', 'motricity'),
	('Aromatismo', 'perception'),
	('Contato', 'perception'),
	('Escuta', 'perception'),
	('Gustação', 'perception'),
	('Observação', 'perception')
ON CONFLICT ("name") DO NOTHING;
